$(function(){
//显示第一张图片
$('.pic>li').eq(0).show();
//向右切换
var i=0;
var play=function(){
    i++;
    //判断小圆点是否越界
    i=i>7?0:i;
    $('.pic>li').eq(i).fadeIn(1000).siblings().fadeOut(1000);
    //小圆点跟随切换
    $('#circle>li').eq(i).addClass('active').siblings().removeClass('active');
}
//自动轮播
var timer=setInterval(play,2000);
//鼠标悬浮暂停轮播，移出继续
$('#container').mouseover(
    function(){
        clearInterval(timer);
    }
);
    $('#container').mouseout(
        function(){
            timer=setInterval(play,1500);
        }
    );
//箭头功能
//向右
    $('.arrow_right').click(
        function(){
            play();
        }
    );
//向左
    var moveLeft=function(){
        i--;
        i=i<0?7:i;
        $('.pic>li').eq(i).fadeIn(600).siblings().fadeOut(600);
        //小圆点跟随切换
        $('#circle>li').eq(i).addClass('active').siblings().removeClass('active');
    }
    $('.arrow_left').click(
        function(){
            moveLeft();
        }
    );
//小圆点跟随切换
$('#circle>li').hover(function(e){
    $target=$(e.target).index();
    //console.log($target);
    i=$target;
    $('.pic>li').eq(i).fadeIn(600).siblings().fadeOut(600);
    $('#circle>li').eq(i).addClass('active').siblings().removeClass('active');
});
})